# Generated by Django 6.1.1 on 2026-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('age_rating', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
